using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MADITP2._0.Enums
{
    public enum EnumExcel
    {
        REPORT_LEVEL_EPC,
        REPORT_MASTER_VERIFICATOR,
        REPORT_VERIFICATOR_SCHEDULE_ASSIGNMENT,
        REPORT_VERIFICATION_STATUS_DELIVERY_CONFIRMATION,
        REPORT_VERIFICATION_STATUS,
        REPORT_SALES_ORDER_RELEASE,
        REPORT_WAREHOUSE_TRANSFER_OUT,
        REPORT_ENTITY,
        REPORT_BRANCH,
        REPORT_FISCAL_CALENDAR,
        REPORT_SEQUENCE_NUMBER_EDITOR,
        REPORT_MODULE,
        REPORT_TELEMARKETING_PARAMETER,
        REPORT_TELEMARKETING_QUESTION_MASTER,
        REPORT_LIST_KUITANSI_SLIP_PROCESS,
        REPORT_LIST_KUITANSI_SLIP_UNPROCESS_ALL,

        REPORT_CASH_BANK_TYPE,
        REPORT_CASH_CODE,
        REPORT_VOUCHER_TYPE,
        REPORT_CREDIT_LIMIT,
        REPORT_CURRENCY_CODE,
        REPORT_BANK_GROUP,
        REPORT_COLLECTOR_MASTER,
        REPORT_MASTER_SU_HONGKONG,
        REPORT_MASTER_CATEGORY_PRODUCT,
        REPORT_MASTER_BRAND,
        REPORT_MASTER_SUBBRAND1,
        REPORT_MASTER_SUBBRAND2,
        REPORT_GENERAL_PARAMETER,
        REPORT_MASTER_PRODUCT,
        REPORT_MASTER_CASH_BANK,
        REPORT_CUGS,
        REPORT_RESI,
        REPORT_JNT,
        REPORT_UPLOAD_DATA_PCP

    }
}
